### ISSUE TITLE
Flake8 complaints in Travis

### ISSUE THREAD

**Issue by XVilka** [williballenthin/python-idb#43]
```
0.03s$ ls $(find /home/travis/virtualenv/ -name "capstone" -type d | sort | head -n 1)
arm64_const.py	 __init__.pyc	 ppc.pyc	  x86_const.pyc
arm64_const.pyc  lib		 sparc_const.py   x86.py
arm64.py	 libcapstone.so  sparc_const.pyc  x86.pyc
arm64.pyc	 mips_const.py	 sparc.py	  xcore_const.py
arm_const.py	 mips_const.pyc  sparc.pyc	  xcore_const.pyc
arm_const.pyc	 mips.py	 systemz.py	  xcore.py
arm.py		 mips.pyc	 systemz.pyc	  xcore.pyc
arm.pyc		 ppc_const.py	 sysz_const.py
include		 ppc_const.pyc	 sysz_const.pyc
__init__.py	 ppc.py		 x86_const.py
0.24s$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to 'module' object has no attribute 'break_around_binary_operator'.
```

**Comment by syntroniks** [comment]
related: https://gitlab.com/pycqa/flake8/issues/406 ?

**Comment by williballenthin** [comment]
yeah, that's pretty much the root cause that I found @syntroniks 

right now, patiently waiting for flake8 to start working again...

**Comment by williballenthin** [comment]
as of [pycqa#230](https://gitlab.com/pycqa/flake8/merge_requests/230), flake8 works with pycodestyle 2.4.0. however, I don't believe there's a release of flake8 quite yet. so, we can install directly from the git repo as a zip archive:

    https://gitlab.com/pycqa/flake8/-/archive/9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d/flake8-9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d.zip

Commit 9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d simply is the latest commit as of today, which seems to work ok. I don't want to trace `master`, as that's not guaranteed to remain stable.

**Comment by williballenthin** [comment]
fixed in 99178f804730dad59a10b70dadc5ca659e342e15
